"""Add colunas HLTB

Revision ID: 9105ee06623b
Revises: be4fb363765c
Create Date: 2026-08-06 20:42:37.913611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9105ee06623b'
down_revision = 'be4fb363765c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_historia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_extra', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tempo_completo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_column('tempo_completo')
        batch_op.drop_column('tempo_extra')
        batch_op.drop_column('tempo_historia')

    # ### end Alembic commands ###
